# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x

      - run: npm ci
      - run: npm run build
      - run: npm run zip

      - name: Set env var to tag version
        run: echo ::set-env name=VERSION_TAG::${GITHUB_REF#refs/*/}

      - name: Set env var to manifest version
        run: echo ::set-env name=VERSION_MANIFEST::$(node extract-version.js)

      - name: Test the version vars
        run: |
          echo VERSION_TAG:$VERSION_TAG 
          echo VERSION_MANIFEST:$VERSION_MANIFEST
          echo $VERSION_TAG == $VERSION_MANIFEST
          if: ${{ env.VERSION_TAG == env.VERSION_MANIFEST }}

      - name: Add version to zip file name
        run: mv prstatus.zip prstatus-${{env.VERSION_TAG}}.zip

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./prstatus-${{env.VERSION_TAG}}.zip
          gzip: false
