# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set env var to tag version
        run: echo "VERSION_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set env var to manifest version
        run: echo "VERSION_MANIFEST=$(node version.js)" >> $GITHUB_ENV

      - name: Ensure tag version matches the manifest version
        run: |
          echo VERSION_TAG=$VERSION_TAG 
          echo VERSION_MANIFEST=$VERSION_MANIFEST
          echo ${VERSION_TAG/-rc*/} == $VERSION_MANIFEST
          [ "${VERSION_TAG/-rc*/}" = "$VERSION_MANIFEST" ]

      - name: Building artefacts
        run: |
          npm ci
          npm run build
          npm run zip
          npm run zip:firefox

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: >
            .artefacts/prstatus-${{ env.VERSION_TAG }}.zip
            .artefacts/prstatus-firefox-${{ env.VERSION_TAG }}.zip
          gzip: false
